### PR TITLE
adapt to the new  vala loop api

### LINKED ISSUE #171: Build failure with vala 0.50.1.214-40a6
Vala-Language-Server is not buildable anymore with the recent vala compiler.
```
vala --version
Vala 0.50.1.214-40a6
```
meson configure without a problem but ninja emits those errors

```
../src/list_symbols.vala:387.5-387.35: error: `Vls.ListSymbols.visit_loop': no suitable method found to override
    public override void visit_loop (Vala.Loop stmt) {
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/codehelp/find_symbol.vala:502.5-502.35: error: `Vls.FindSymbol.visit_loop': no suitable method found to override
    public override void visit_loop (Vala.Loop stmt) {
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/codehelp/find_scope.vala:204.5-204.35: error: `Vls.FindScope.visit_loop': no suitable method found to override
    public override void visit_loop (Vala.Loop stmt) {
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/codehelp/symbolvisitor.vala:454.5-454.35: error: `Vls.SymbolVisitor.visit_loop': no suitable method found to override
    public override void visit_loop (Loop stmt) {
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 4 error(s), 0 warning(s)
ninja: build stopped: subcommand failed.
```

### PR DESCRIPTION
**Pull request by aeldemery**
Vala introduce a new common class for all looping construct in this commit `b3ee5b0f` `Rename Loop to LoopStatement and introduce a common base class`

This MR rename all occurrences accordingly.
closes #171

### CODE REVIEW

**Comment by Prince781** [comment]
It looks like it's `Vala.Loop`, not `Vala.LoopStatement`

**Comment by Prince781** [comment]
Okay, looks good to me now.

**Comment by Prince781** [comment]
Thanks for your commit @aeldemery

**Comment by aeldemery** [comment]
@Prince781 thank you for improving `VLS`.

**Pull request merged**
