### PR TITLE
GNOME Builder integration

### PR DESCRIPTION
**Pull request by Prince781**
Still kind of buggy at the moment.

### CODE REVIEW

**Comment by minkir014** [comment]
Is this a build system? I mean this only builds right.

**Comment by Prince781** [comment]
This branch provides a VLS plugin for the GNOME Builder IDE.

**Comment by benwaffle** [comment]
nice! does it work?

**Comment by Prince781** [comment]
It's still a work in progress (let's say the support is experimental for now), but I merged because I fixed some other things in this branch. 

For some reason, you have to `kill vala-language-server` once and then it just works. I'll see if I can fix this later.

**Comment by Prince781** [comment]
Now this means that you can use VLS in VS Code, vim, and GNOME builder.

**Pull request merged**
