### PR TITLE
Use libdir instead of a hardcoded lib directory

### PR DESCRIPTION
**Pull request by nahuelwexd**

### CODE REVIEW

**Comment by Prince781** [comment]
Hi @nahuelwexd 

Could you please use two spaces for indentation? Thanks.

**Comment by nahuelwexd** [comment]
Done

**Comment by Prince781** [comment]
@nahuelwexd Can you squash these commits? I could squash and merge but I'd prefer to rebase instead.

**Comment by benwaffle** [comment]
squash and merge will put it as the latest commit

**Comment by Prince781** [comment]
@benwaffle won't it add a commit that says "merge ..." to the history?

**Comment by benwaffle** [comment]
Yes, "merged PR #75", but I dont believe it's a merge commit

**Comment by nahuelwexd** [comment]
Well that didn't work as expected :sweat_smile:

**Comment by Prince781** [comment]
@nahuelwexd nevertheless I've fixed your commit and applied it. Thanks for the contribution!

**Pull request closed without merging**
