### PR TITLE
Fix brokenness with meson custom targets

### PR DESCRIPTION
**Pull request by zxzax**
I was trying to use the language server with a project that uses [vala-dbus-binding-tool](https://github.com/freesmartphone/vala-dbus-binding-tool) and I noticed it was failing to build the generated targets. The way vala-language-server replaces special args is not quite accurate to the way meson does it, and some custom targets are skipped entirely; hopefully this PR should fix both. This PR is useful by itself but there is an additional problem with meson where it doesn't export custom target dependencies correctly. That is fixed by this other upstream change to meson I submitted: https://github.com/mesonbuild/meson/pull/8674

I didn't do any substantial testing with autotools projects so probably someone should check to see if this PR accidentally broke something there.

### CODE REVIEW

**Comment by zxzax** [comment]
Technically I think they are supported when using the compile_commands.json mode? Not sure, I never tried it.

**Comment by Prince781** [comment]
> Technically I think they are supported when using the compile_commands.json mode? Not sure, I never tried it.

We have a backend for _just_ compile_commands.json (see CcProject.vala). The Meson backend also does some parsing of `compile_commands.json` because Meson introspection has a lot of bugs, as you've probably noticed.

**Comment by Prince781** [comment]
So this patch causes a regression at least with two projects: Geary and Budgie Desktop mainline. After this patch we're getting configuration errors where two or more build targets produce the same file.

Budgie Desktop:
```
(vala-language-server:127955): vls-WARNING **: 20:13:57.820: server.vala:213: Failed to initialize Meson project - There are two build targets that produce the same file! Both 8012fdb@@budgie-enums.h@cus and 8012fdb@@budgie-enums.h@cus produce /tmp/vls-meson-3448219481-CLF210/src/plugin/budgie-enums.h
``

Geary:
```
(vala-language-server:128449): vls-WARNING **: 20:15:26.300: server.vala:213: Failed to initialize Meson project - There are two build targets that produce the same file! Both 318f0fc@@engine_internal_header_fixup@cus and 318f0fc@@geary-engine@sta produce /tmp/vls-meson-579313498-UDP010/src/engine/geary-engine-internal.vapi
```

What was the project you were originally trying to get VLS to work with?

**Comment by Prince781** [comment]
Without the second commit ("Build all custom targets"), there is no regression.

**Comment by zxzax** [comment]
I'll test it out with Geary. Here is a test project I was using: https://gitlab.gnome.org/jf/vala-dbus-test. To test out the patch, I was opening `main.vala` there and seeing if I can get completion on `TestInterface`. Without the patch, it fails to load the symbols because it doesn't build the generated vala file at all. With the patch and with the meson patch, I am able to get completions on the object, but there is still an error on the `get_proxy_sync` line for some reason... which has been good enough for me, but maybe it needs more investigation.

**Comment by Prince781** [comment]
Just FYI, I'm working on a fix. There's something to work with here, but other components need to be changed to make this work. I don't want you to waste your time duplicating my effort.

**Comment by zxzax** [comment]
Thanks, I'm still not entirely sure why only `.in` files were being processed in `BuildTask`...

**Comment by Prince781** [comment]
I'm closing this and instead I want to continue the discussion at #180, where you can tell me whether the PR addresses all of your concerns.

**Pull request closed without merging**
