### PR TITLE
CI

### PR DESCRIPTION
**Pull request by benwaffle**

### CODE REVIEW

**Comment by benwaffle** [comment]
@Prince781 not sure why this is failing. `client.reply()` can take null. Can you take a look?

**Comment by benwaffle** [comment]
Ah. the version of jsonrpc-glib that is installed on ubuntu has

```vala
public bool reply (GLib.Variant id, GLib.Variant result, GLib.Cancellable? cancellable = null) throws GLib.Error;
```

**Comment by Prince781** [comment]
> Is the solution to remove --fatal-warnings?

No. Why is it failing? We should have a try/catch around all uses of `Client.reply`.

**Comment by benwaffle** [comment]
The error isn't unhandled exception. It's
```
../main.vala:744.35-744.38: warning: Argument 2: Cannot pass null to non-null parameter type
                client.reply (id, null);
                                  ^^^^
```

Because libjsonrpc-glib on Ubuntu has this signature for `reply`:
```
public bool reply (GLib.Variant id, GLib.Variant result, GLib.Cancellable? cancellable = null) throws GLib.Error;
```

But we're using a newer version locally which has this signature:
```
public bool reply (GLib.Variant id, GLib.Variant? result, GLib.Cancellable? cancellable = null) throws GLib.Error;
```

Notice how `result` is nullable in newer versions.

Some options:
- remove `--fatal-warnings`
- can we silence warnings only around that block of code?
- try to install a newer version of jsonrpc-glib in the CI environment
- something else

**Comment by Prince781** [comment]
On Tue, Aug 13, 2019 at 10:24 AM, Ben Iofel <notifications@github.com> 
wrote:
> try to install a newer version of jsonrpc-glib in the CI environment

Try this first.

**Comment by benwaffle** [comment]
We should support VLS on latest version of ubuntu though

**Comment by Prince781** [comment]
```c
gboolean
jsonrpc_client_reply (JsonrpcClient  *self,
                      GVariant       *id,
                      GVariant       *result,
                      GCancellable   *cancellable,
                      GError        **error)
{
  JsonrpcClientPrivate *priv = jsonrpc_client_get_instance_private (self);
  g_autoptr(GVariant) message = NULL;
  GVariantDict dict;
  gboolean ret;

  g_return_val_if_fail (JSONRPC_IS_CLIENT (self), FALSE);
  g_return_val_if_fail (id != NULL, FALSE);
  g_return_val_if_fail (!cancellable || G_IS_CANCELLABLE (cancellable), FALSE);

  if (!jsonrpc_client_check_ready (self, error))
    return FALSE;

  if (result == NULL)
    result = g_variant_new_maybe (G_VARIANT_TYPE_VARIANT, NULL);
// ...
}
```

It looks like passing in `null` as the result gets turned into a `Variant.maybe`, so perhaps we could just pass in `new Variant.maybe(VariantType.VARIANT, null)` to `client.reply()`.

**Comment by Prince781** [comment]
Well, looks like it works now. I'll leave it up to you to merge when you're done.

**Comment by Prince781** [comment]
I think maybe you might want to squash some or all of these commits.

**Comment by benwaffle** [comment]
thanks

**Pull request merged**
